[groups]
new-hosts = { ip = "10.236.0.190", port = "22", user = "root", password = "root" }

[qwe]
123 = { ip = "192.1.1.1", port = "22", user = "rr", password = "rr" }

[asd]
qwer = { ip = "191.1.1.1", port = "22", user = "we", password = "we" }

[lyuda]
lusi = { ip = "192.168.31.100", port = "22", user = "pmk", password = "chiiiina" }

