[groups-1]
host1 = { ip = "192.168.31.101", port = "22", user = "pmk", password = "chiiiina" }
host2 = { ip = "2.2.2.2", port = "22", user = "pmk" , key_path = "/path/to/key" }

[groups-12]
host1 = { ip = "192.168.31.100", port = "22", user = "pmk", password = "chiiiina" }
